/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.barroso.kafka.avroclient.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Payment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8800885514206046515L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Payment\",\"namespace\":\"br.com.barroso.kafka.avroclient.avro\",\"fields\":[{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Payment code.\"},{\"name\":\"order\",\"type\":{\"type\":\"record\",\"name\":\"Order\",\"fields\":[{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Order code.\"},{\"name\":\"customer\",\"type\":{\"type\":\"record\",\"name\":\"Customer\",\"fields\":[{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer code.\"},{\"name\":\"first_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer first name.\"},{\"name\":\"last_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer last code.\"},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer email.\",\"default\":null}]},\"doc\":\"Customer.\"},{\"name\":\"products\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Product\",\"fields\":[{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Product code.\"},{\"name\":\"product_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Product name.\"},{\"name\":\"product_price\",\"type\":\"double\",\"doc\":\"Product price.\"},{\"name\":\"product_amount\",\"type\":\"int\",\"doc\":\"Product amount.\",\"default\":1}]}},\"doc\":\"Product list.\"}]},\"doc\":\"Customer order.\"},{\"name\":\"total_quantity\",\"type\":\"int\",\"doc\":\"Total order quantity.\"},{\"name\":\"total_value\",\"type\":\"double\",\"doc\":\"Total order value.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Payment> ENCODER =
      new BinaryMessageEncoder<Payment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Payment> DECODER =
      new BinaryMessageDecoder<Payment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Payment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Payment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Payment>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Payment to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Payment from a ByteBuffer. */
  public static Payment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Payment code. */
   private java.lang.String code;
  /** Customer order. */
   private br.com.barroso.kafka.avroclient.avro.Order order;
  /** Total order quantity. */
   private int total_quantity;
  /** Total order value. */
   private double total_value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Payment() {}

  /**
   * All-args constructor.
   * @param code Payment code.
   * @param order Customer order.
   * @param total_quantity Total order quantity.
   * @param total_value Total order value.
   */
  public Payment(java.lang.String code, br.com.barroso.kafka.avroclient.avro.Order order, java.lang.Integer total_quantity, java.lang.Double total_value) {
    this.code = code;
    this.order = order;
    this.total_quantity = total_quantity;
    this.total_value = total_value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return code;
    case 1: return order;
    case 2: return total_quantity;
    case 3: return total_value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: code = (java.lang.String)value$; break;
    case 1: order = (br.com.barroso.kafka.avroclient.avro.Order)value$; break;
    case 2: total_quantity = (java.lang.Integer)value$; break;
    case 3: total_value = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'code' field.
   * @return Payment code.
   */
  public java.lang.String getCode() {
    return code;
  }


  /**
   * Gets the value of the 'order' field.
   * @return Customer order.
   */
  public br.com.barroso.kafka.avroclient.avro.Order getOrder() {
    return order;
  }


  /**
   * Gets the value of the 'total_quantity' field.
   * @return Total order quantity.
   */
  public java.lang.Integer getTotalQuantity() {
    return total_quantity;
  }


  /**
   * Gets the value of the 'total_value' field.
   * @return Total order value.
   */
  public java.lang.Double getTotalValue() {
    return total_value;
  }


  /**
   * Creates a new Payment RecordBuilder.
   * @return A new Payment RecordBuilder
   */
  public static br.com.barroso.kafka.avroclient.avro.Payment.Builder newBuilder() {
    return new br.com.barroso.kafka.avroclient.avro.Payment.Builder();
  }

  /**
   * Creates a new Payment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Payment RecordBuilder
   */
  public static br.com.barroso.kafka.avroclient.avro.Payment.Builder newBuilder(br.com.barroso.kafka.avroclient.avro.Payment.Builder other) {
    return new br.com.barroso.kafka.avroclient.avro.Payment.Builder(other);
  }

  /**
   * Creates a new Payment RecordBuilder by copying an existing Payment instance.
   * @param other The existing instance to copy.
   * @return A new Payment RecordBuilder
   */
  public static br.com.barroso.kafka.avroclient.avro.Payment.Builder newBuilder(br.com.barroso.kafka.avroclient.avro.Payment other) {
    return new br.com.barroso.kafka.avroclient.avro.Payment.Builder(other);
  }

  /**
   * RecordBuilder for Payment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Payment>
    implements org.apache.avro.data.RecordBuilder<Payment> {

    /** Payment code. */
    private java.lang.String code;
    /** Customer order. */
    private br.com.barroso.kafka.avroclient.avro.Order order;
    private br.com.barroso.kafka.avroclient.avro.Order.Builder orderBuilder;
    /** Total order quantity. */
    private int total_quantity;
    /** Total order value. */
    private double total_value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.barroso.kafka.avroclient.avro.Payment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order)) {
        this.order = data().deepCopy(fields()[1].schema(), other.order);
        fieldSetFlags()[1] = true;
      }
      if (other.hasOrderBuilder()) {
        this.orderBuilder = br.com.barroso.kafka.avroclient.avro.Order.newBuilder(other.getOrderBuilder());
      }
      if (isValidValue(fields()[2], other.total_quantity)) {
        this.total_quantity = data().deepCopy(fields()[2].schema(), other.total_quantity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.total_value)) {
        this.total_value = data().deepCopy(fields()[3].schema(), other.total_value);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Payment instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.barroso.kafka.avroclient.avro.Payment other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order)) {
        this.order = data().deepCopy(fields()[1].schema(), other.order);
        fieldSetFlags()[1] = true;
      }
      this.orderBuilder = null;
      if (isValidValue(fields()[2], other.total_quantity)) {
        this.total_quantity = data().deepCopy(fields()[2].schema(), other.total_quantity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.total_value)) {
        this.total_value = data().deepCopy(fields()[3].schema(), other.total_value);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'code' field.
      * Payment code.
      * @return The value.
      */
    public java.lang.String getCode() {
      return code;
    }

    /**
      * Sets the value of the 'code' field.
      * Payment code.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder setCode(java.lang.String value) {
      validate(fields()[0], value);
      this.code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * Payment code.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'code' field.
      * Payment code.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder clearCode() {
      code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'order' field.
      * Customer order.
      * @return The value.
      */
    public br.com.barroso.kafka.avroclient.avro.Order getOrder() {
      return order;
    }

    /**
      * Sets the value of the 'order' field.
      * Customer order.
      * @param value The value of 'order'.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder setOrder(br.com.barroso.kafka.avroclient.avro.Order value) {
      validate(fields()[1], value);
      this.orderBuilder = null;
      this.order = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'order' field has been set.
      * Customer order.
      * @return True if the 'order' field has been set, false otherwise.
      */
    public boolean hasOrder() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'order' field and creates one if it doesn't exist yet.
     * Customer order.
     * @return This builder.
     */
    public br.com.barroso.kafka.avroclient.avro.Order.Builder getOrderBuilder() {
      if (orderBuilder == null) {
        if (hasOrder()) {
          setOrderBuilder(br.com.barroso.kafka.avroclient.avro.Order.newBuilder(order));
        } else {
          setOrderBuilder(br.com.barroso.kafka.avroclient.avro.Order.newBuilder());
        }
      }
      return orderBuilder;
    }

    /**
     * Sets the Builder instance for the 'order' field
     * Customer order.
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder setOrderBuilder(br.com.barroso.kafka.avroclient.avro.Order.Builder value) {
      clearOrder();
      orderBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'order' field has an active Builder instance
     * Customer order.
     * @return True if the 'order' field has an active Builder instance
     */
    public boolean hasOrderBuilder() {
      return orderBuilder != null;
    }

    /**
      * Clears the value of the 'order' field.
      * Customer order.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder clearOrder() {
      order = null;
      orderBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'total_quantity' field.
      * Total order quantity.
      * @return The value.
      */
    public java.lang.Integer getTotalQuantity() {
      return total_quantity;
    }

    /**
      * Sets the value of the 'total_quantity' field.
      * Total order quantity.
      * @param value The value of 'total_quantity'.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder setTotalQuantity(int value) {
      validate(fields()[2], value);
      this.total_quantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'total_quantity' field has been set.
      * Total order quantity.
      * @return True if the 'total_quantity' field has been set, false otherwise.
      */
    public boolean hasTotalQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'total_quantity' field.
      * Total order quantity.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder clearTotalQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'total_value' field.
      * Total order value.
      * @return The value.
      */
    public java.lang.Double getTotalValue() {
      return total_value;
    }

    /**
      * Sets the value of the 'total_value' field.
      * Total order value.
      * @param value The value of 'total_value'.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder setTotalValue(double value) {
      validate(fields()[3], value);
      this.total_value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'total_value' field has been set.
      * Total order value.
      * @return True if the 'total_value' field has been set, false otherwise.
      */
    public boolean hasTotalValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'total_value' field.
      * Total order value.
      * @return This builder.
      */
    public br.com.barroso.kafka.avroclient.avro.Payment.Builder clearTotalValue() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Payment build() {
      try {
        Payment record = new Payment();
        record.code = fieldSetFlags()[0] ? this.code : (java.lang.String) defaultValue(fields()[0]);
        if (orderBuilder != null) {
          record.order = this.orderBuilder.build();
        } else {
          record.order = fieldSetFlags()[1] ? this.order : (br.com.barroso.kafka.avroclient.avro.Order) defaultValue(fields()[1]);
        }
        record.total_quantity = fieldSetFlags()[2] ? this.total_quantity : (java.lang.Integer) defaultValue(fields()[2]);
        record.total_value = fieldSetFlags()[3] ? this.total_value : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Payment>
    WRITER$ = (org.apache.avro.io.DatumWriter<Payment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Payment>
    READER$ = (org.apache.avro.io.DatumReader<Payment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
